# Generated by Django 5.1.3 on 2025-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initialbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitialBalance',
        ),
    ]
