# Generated by Django 5.1.3 on 2025-04-07 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_initialbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=50)),
                ('goal_amount', models.FloatField()),
                ('goal_start_date', models.DateField()),
                ('goal_end_date', models.DateField()),
                ('goal_income_categories', models.CharField(default=None)),
                ('goal_expense_categories', models.CharField(default=None)),
                ('goal_type', models.CharField(max_length=20)),
                ('goal_description', models.CharField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
