# Generated by Django 5.1.3 on 2025-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_new_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_goal',
            name='goal_description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='new_goal',
            name='goal_expense_categories',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='new_goal',
            name='goal_income_categories',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
