# Generated by Django 5.1.3 on 2025-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_balance',
            field=models.FloatField(default=0),
        ),
    ]
